development:
  adapter: redis
  url: redis://redistogo:8a89efb80e40ce22ab195489449ec9fd@crestfish.redistogo.com:9307/

test:
  adapter: redis
  url: redis://redistogo:8a89efb80e40ce22ab195489449ec9fd@crestfish.redistogo.com:9307/

production:
  adapter: redis
  url: redis://redistogo:8a89efb80e40ce22ab195489449ec9fd@crestfish.redistogo.com:9307/
